Repository Mini-Team-6/Mini-Team-6-Frontend, pull requests merged in 2023-11, with the labels that each got.

#2 [#1] chore : 라이브러리 설치
  package-lock.json
  package.json
Labels: chore

#4 [#3] chore : 프로젝트 라우터 세팅 및 글로벌 스타일 추가
  index.html
  src/App.css
  src/App.tsx
  src/api/.gitkeep
  src/assets/react.svg
  src/components/.gitkeep
  src/components/Header.tsx
  src/hook/.gitkeep
  src/index.css
  src/main.tsx
  src/pages/cartPage/CartPage.tsx
  src/pages/detailPage/DetailPage.tsx
  src/pages/loginPage/LoginPage.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/reservationPage/ReservationPage.tsx
  src/pages/searchPage/SearchPage.tsx
  src/routes/HeaderRoute.tsx
  src/routes/MainStyleRoute.tsx
  src/store/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
Labels: chore

#10 [#8] feat : 공통 헤더 컴포넌트 1차 마무리
  package-lock.json
  package.json
  public/assets/icons/arrowLeft.svg
  public/assets/icons/arrowRight.svg
  public/assets/icons/arrowUp.svg
  public/assets/icons/cart.svg
  public/assets/icons/list.svg
  public/assets/logo/headerLogo.svg
  src/App.tsx
  src/components/Header.tsx
  src/components/Header/Header.tsx
  src/components/Header/Sidebar.tsx
  src/routes/HeaderRoute.tsx
  src/vite-env.d.ts
  vite.config.ts
Labels: feat

#13 [#12] design : 헤더 스타일 변경 / 글로벌 스타일 스크롤바 추가 / 로그인 페이지 헤더 제거
  src/components/Header/Header.tsx
  src/components/Header/Sidebar.tsx
  src/main.tsx
  src/routes/MainStyleRoute.tsx
Labels: design

#16 [#14] fix : asset 폴더 위치 변경 및 min-height 조정
  src/assets/icons/arrowLeft.svg
  src/assets/icons/arrowRight.svg
  src/assets/icons/arrowUp.svg
  src/assets/icons/cart.svg
  src/assets/icons/list.svg
  src/assets/logo/headerLogo.svg
  src/components/Header/Header.tsx
  src/components/Header/Sidebar.tsx
  src/routes/MainStyleRoute.tsx
Labels: fix

#18 [#15] feat : 페이지 스타일 수정 및 MockData 연결
  public/mock/roomsData.json
  public/mockImage.png
  src/assets/icons/Calendar.svg
  src/assets/icons/User.svg
  src/components/Cart/CartSelection.tsx
  src/components/Detail/DetailDate.tsx
  src/components/Detail/DetailDateAndCount.tsx
  src/components/Detail/DetailSectionBottom.tsx
  src/components/Detail/DetailSectionBottomBox.tsx
  src/components/Detail/DetailSectionTop.tsx
  src/hook/useDate.ts
  src/pages/cartPage/CartPage.tsx
  src/pages/detailPage/DetailPage.tsx
Labels: feat

#22 [#14] feat : 검색 페이지 레이아웃 작성 및 기타
  package-lock.json
  package.json
  public/mock/searchData.json
  src/api/mockSearchApi.ts
  src/assets/icons/search.svg
  src/components/Header/Header.tsx
  src/components/Header/Sidebar.tsx
  src/main.tsx
  src/pages/searchPage/LocationSelect.tsx
  src/pages/searchPage/SearchInput.tsx
  src/pages/searchPage/SearchPage.tsx
  src/pages/searchPage/SearchReslutList.tsx
Labels: feat

#25 [#6] feat: 예약 페이지 퍼블리싱
  src/assets/checkIcon.svg
  src/assets/goBackIcon.svg
  src/assets/infoIcon.svg
  src/assets/kakaopayIcon.png
  src/assets/personIcon.svg
  src/components/Input.tsx
  src/components/Reservation/ActualUserInfoSection.tsx
  src/components/Reservation/Caution.tsx
  src/components/Reservation/Checkbox.tsx
  src/components/Reservation/DateInfoWrapper.tsx
  src/components/Reservation/PaymentCautions.tsx
  src/components/Reservation/PaymentOptionBox.tsx
  src/components/Reservation/PaymentSelectionSection.tsx
  src/components/Reservation/ReservationInfoSection.tsx
  src/components/Reservation/ReservationPersonInfoSection.tsx
  src/components/Reservation/constants.tsx
  src/components/Reservation/reservationStyles.ts
  src/pages/reservationPage/ReservationPage.tsx
  src/utils/addCommasToNumber.ts
Labels: feat

#29 feat: 로그인, 회원가입페이지 기능구현
  package-lock.json
  package.json
  src/components/Input.tsx
  src/components/JoinModal.tsx
  src/pages/loginPage/LoginPage.tsx
  src/pages/loginPage/SignupPage.tsx
Labels: feat

#32 [#24] feat : 무한스크롤 구현
  package-lock.json
  public/mock/searchData.json
  src/api/config.ts
  src/api/mockSearchApi.ts
  src/api/search.ts
  src/assets/icons/defaultHotel.svg
  src/components/Header/Header.tsx
  src/hook/useIntersect.ts
  src/pages/searchPage/LocationSelect.tsx
  src/pages/searchPage/SearchInput.tsx
  src/pages/searchPage/SearchPage.tsx
  src/pages/searchPage/SearchReslutList.tsx
  src/types/searchResult.ts
Labels: feat

#37 [#24] refactor : 검색 페이지 state -> queryString 으로 데이터 관리 방법 변경
  src/pages/searchPage/LocationSelect.tsx
  src/pages/searchPage/SearchInput.tsx
  src/pages/searchPage/SearchPage.tsx
  src/pages/searchPage/SearchReslutList.tsx
Labels: feat

#38 Refact: 상태관리 zustand라이브러리로 변경
  package-lock.json
  package.json
  src/App.tsx
  src/components/Context/UserContext.tsx
  src/components/Header/Sidebar.tsx
  src/components/Store/UserStore.tsx
  src/pages/loginPage/LoginPage.tsx
  src/pages/loginPage/SignupPage.tsx
Labels: refactor

#42 [#41] feat : 사이드바 메뉴버튼 추가
  src/components/Header/Header.tsx
  src/components/Header/Sidebar.tsx
Labels: feat

#49 [#43] design : 검색페이지 로딩시 스켈레톤 디자인 추가
  src/pages/searchPage/SearchPage.tsx
  src/pages/searchPage/SearchReslutList.tsx
  src/pages/searchPage/SkeletonSearchResultList.tsx
Labels: design

#56 [#55] chore : playwright 설치 및 github action 확인
  .github/workflows/playwright.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  tests/example.spec.ts
Labels: chore

#57 [#54] feat : 검색 결과 없을 시 화면 추가
  src/api/search.ts
  src/assets/icons/noResult.svg
  src/pages/searchPage/SearchReslutList.tsx
  src/pages/searchPage/SkeletonSearchResultList.tsx
Labels: feat

#48 Refact: zustand로 상태관리했던 부분 디버깅과 마이페이지 리팩토링
  src/components/Header/Sidebar.tsx
  src/pages/loginPage/LoginPage.tsx
  src/pages/myPage/MyPage.tsx
Labels: refactor

#66 feat : 로그인 성공 실패 테스트 추가
  tests/loginPage.spec.ts
Labels: feat, test

#67 [#64] feat : 회원가입 중복 체크 테스트 추가
  tests/loginPage.spec.ts
Labels: feat, test

#68 [#64] feat : 테스트 설정 변경 및 검섹페이지 테스트 수정
  playwright.config.ts
  tests/searchPage.spec.ts
Labels: feat, test

#72 [#65] feat: 디테일 페이지 렌더링 방식 변경 및 장바구니 페이지 기능 구현 및 버그 수정
  public/mock/MockCartData.json
  src/api/cart.ts
  src/api/detail.ts
  src/components/Cart/CartNoReservation.tsx
  src/components/Cart/CartResevation.tsx
  src/components/Cart/CartSection.tsx
  src/components/Cart/CartSectionBox.tsx
  src/components/Cart/CartSelection.tsx
  src/components/Detail/DatePickModal.tsx
  src/components/Detail/DetailDateAndCount.tsx
  src/components/Detail/DetailSectionBottom.tsx
  src/components/Detail/DetailSectionBottomBox.tsx
  src/hook/useDate.ts
  src/pages/cartPage/CartPage.tsx
  src/pages/detailPage/DetailPage.tsx
  src/store/accommodationList.ts
  src/store/cartList.ts
  src/store/pickCartList.ts
Labels: feat

#76 [#75] refactor : 검색페이지 무한스크롤 개선
  src/pages/searchPage/SearchReslutList.tsx
Labels: refactor

#77 마이페이지 수정기능 추가
  src/pages/myPage/MyPage.tsx
Labels: refactor

#79 feat: 401 에러 핸들링 함수 추가 및 api 일부 수정
  src/App.tsx
  src/api/detail.ts
  src/api/reservation.ts
  src/assets/dummy.png
  src/components/Detail/DetailSectionBottom.tsx
  src/components/Header/Header.tsx
  src/components/Header/Sidebar.tsx
  src/components/Reservation/HistoryRoom.tsx
  src/components/Reservation/ReservationHistoryItem.tsx
  src/pages/detailPage/DetailPage.tsx
  src/pages/loginPage/LoginPage.tsx
  src/pages/reservationPage/ReservationHistoryPage.tsx
  src/pages/reservationPage/ReservationPage.tsx
  src/utils/formatOrCalculateData.ts
Labels: feat

#81 Fix: 미사용 변수 제거
  src/components/Reservation/HistoryRoom.tsx
  src/pages/reservationPage/ReservationHistoryPage.tsx
Labels: fix

#84 [#44] Feat: 예약 내역 페이지 api 연동 완료 및 상세보기 경로 추가
  src/components/Reservation/ActualUserInfoSection.tsx
  src/components/Reservation/HistoryRoom.tsx
  src/components/Reservation/ReservationHistoryItem.tsx
  src/components/Reservation/ReservationInfoSection.tsx
  src/components/Reservation/ReservationPersonInfoSection.tsx
  src/pages/reservationPage/ReservationHistoryPage.tsx
Labels: feat

#85 Fix: 불필요한 console.log 제거
  src/pages/reservationPage/ReservationHistoryPage.tsx
Labels: fix

#90 Feat: 예약페이지 테스트코드
  src/components/Reservation/ReservationHistoryItem.tsx
  tests/reservationPage.spec.ts
Labels: feat

#91 docs : readme.md 업데이트
  README.md
Labels: docs
